async page => {
  const results = [];
  const assert = (value, message) => { if (!value) throw new Error(message); results.push(message); };
  const text = async id => (await page.locator('#' + id).textContent()).trim();
  const counts = async () => Promise.all(['stat-total', 'stat-active', 'stat-week', 'stat-offer'].map(text));
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.setViewportSize({ width: 1440, height: 1100 });
  assert((await counts()).join(',') === '8,6,4,1', '初始统计为 8 / 6 / 4 / 1');
  const downloadPromise = page.waitForEvent('download');
  await page.locator('[data-action="export"]').first().click();
  const backup = await downloadPromise;
  await backup.saveAs('qa/demo-backup.json');
  assert(backup.suggestedFilename().endsWith('.json'), '可以导出 JSON 备份');
  const dates = await page.evaluate(() => {
    const key = n => { const d = new Date(); d.setDate(d.getDate() + n); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
    return { today: key(0), six: key(6), seven: key(7) };
  });
  await page.locator('[data-action="add"]').first().click();
  await page.locator('#field-company').fill('   ');
  await page.locator('#field-role').fill('测试岗位');
  await page.locator('#field-city').fill('杭州');
  await page.locator('#record-form button[type="submit"]').click();
  assert(await page.locator('#form-error').isVisible(), '空格公司名称不能保存');
  await page.locator('#field-company').fill('测试公司 <b>安全文本</b>');
  await page.locator('#field-event-at').fill(dates.six + 'T14:00');
  await page.locator('#record-form button[type="submit"]').click();
  assert((await text('form-error')).includes('名称'), '有安排时间时必须填写安排名称');
  await page.locator('#field-event').fill('边界测试面试');
  await page.locator('#field-action').fill('准备技术面试资料');
  await page.locator('#record-form button[type="submit"]').click();
  assert(!(await page.locator('#record-dialog').isVisible()), '新增表单成功关闭');
  assert((await counts()).join(',') === '9,7,5,1', '新增记录更新统计，七天第七日安排被计入');
  assert(await page.locator('.company-name b').count() === 0, '公司字段中的 HTML 作为普通文字显示');
  await page.reload();
  assert((await counts()).join(',') === '9,7,5,1', 'file 协议打开时刷新仍保留新增记录');
  await page.locator('#search').fill('安全文本');
  assert(await page.locator('#jobs-body tr').count() === 1, '关键词筛选正确');
  await page.locator('#jobs-body [data-edit]').click();
  await page.locator('#field-event-at').fill(dates.seven + 'T14:00');
  await page.locator('#record-form button[type="submit"]').click();
  assert(await text('stat-week') === '4', '未来第八日的安排不计入七天统计');
  await page.locator('#search').fill('安全文本');
  await page.locator('#jobs-body [data-edit]').click();
  await page.locator('#field-stage').selectOption('offer');
  await page.locator('#field-action').fill('确认入职');
  await page.locator('#record-form button[type="submit"]').click();
  assert((await counts()).join(',') === '9,6,4,2', '编辑阶段同步更新进行中及 Offer 统计');
  await page.locator('[data-filter="offer"]').click();
  assert(await page.locator('#jobs-body tr').count() === 2, 'Offer 状态筛选正确');
  await page.locator('#search').fill('安全文本');
  await page.locator('#jobs-body [data-delete]').click();
  await page.locator('#confirm-dialog [data-close]').last().click();
  assert(await text('stat-total') === '9', '取消删除保留记录');
  await page.locator('#jobs-body [data-delete]').click();
  await page.locator('#confirm-button').click();
  assert((await counts()).join(',') === '8,6,4,1', '确认删除同步更新统计');
  await page.locator('[data-action="undo"]').click();
  assert(await text('stat-total') === '9', '删除后可以撤销');
  await page.locator('[data-action="clear-demo"]').click();
  await page.locator('#confirm-button').click();
  assert(await text('stat-total') === '1', '清空示例会保留用户新增记录');
  await page.reload();
  assert(await text('stat-total') === '1', '清空示例后刷新不会重新生成示例');
  await page.locator('#jobs-body [data-delete]').click();
  await page.locator('#confirm-button').click();
  await page.reload();
  assert(await text('stat-total') === '0' && await page.locator('.empty-state').isVisible(), '删除全部后刷新保持空状态');
  await page.locator('#import-file').setInputFiles('qa/demo-backup.json');
  await page.locator('#confirm-button').click();
  assert((await counts()).join(',') === '8,6,4,1', '从导出备份恢复全部示例和统计');
  await page.locator('#city-filter').selectOption('杭州');
  assert(await page.locator('#jobs-body tr').count() === 2, '城市筛选正确');
  await page.locator('#stage-filter').selectOption('interview1');
  assert(await page.locator('#jobs-body tr').count() === 1, '城市和阶段支持组合筛选');
  await page.locator('[data-nav="overview"]').first().click();
  const day = page.locator('.day-button').nth(1);
  await day.click();
  assert(await page.locator('#event-list .event-row').count() === 1, '日历可筛选指定日期');
  await day.click();
  assert(await page.locator('#event-list .event-row').count() === 4, '再次点击日期恢复整周安排');
  await page.locator('[data-nav="overview"]').first().click();
  await page.screenshot({ path: 'qa/desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'qa/mobile.png', fullPage: true });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), '390px 手机布局无页面整体溢出');
  await page.locator('[data-action="add"]').first().click();
  await page.screenshot({ path: 'qa/mobile-form.png', fullPage: true });
  assert(await page.locator('#field-company').isVisible(), '手机上可以打开并使用新增表单');
  await page.keyboard.press('Escape');
  assert(!(await page.locator('#record-dialog').isVisible()), 'Escape 可以关闭对话框');
  await page.setViewportSize({ width: 1440, height: 1100 });
  assert(errors.length === 0, '整个验证流程没有 JavaScript 运行错误');
  return { passed: results.length, results, errors };
}
